# Generated by Django 4.2.5 on 2023-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_message_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='message',
            name='text2',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
    ]
