# Generated by Django 4.2.5 on 2023-10-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_rename_text_message_text1_message_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text2',
            field=models.CharField(max_length=255),
        ),
    ]
