# Generated by Django 4.2.5 on 2024-06-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dealer_code',
        ),
    ]
