# Generated by Django 5.0.6 on 2024-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_remove_employee_dealer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='party_code',
            field=models.CharField(default='default_party_code', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='party_name',
            field=models.CharField(default='default_party_code', max_length=100),
            preserve_default=False,
        ),
    ]
