# Generated by Django 5.0.6 on 2024-07-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_employee_party_code_employee_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='line',
            field=models.CharField(default='default_party_code', max_length=50),
        ),
    ]
