# Generated by Django 4.2.5 on 2023-11-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfNo', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('days', models.IntegerField()),
                ('leaveType', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
