# Generated by Django 4.2.5 on 2023-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leaveType',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
