# Generated by Django 4.2.5 on 2023-11-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfNo', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('payslipType', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
