# Generated by Django 4.2.5 on 2023-11-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslipapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_files/'),
        ),
    ]
