# Generated by Django 5.0.6 on 2024-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='line',
            field=models.CharField(default='default_line', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='default_uom', max_length=50),
        ),
    ]
