# Generated by Django 4.2.5 on 2024-06-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_alter_orderitem_product_name_alter_orderitem_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dealer_code',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='outlet',
            new_name='party_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='route',
            new_name='party_name',
        ),
    ]
