# Generated by Django 5.0.6 on 2024-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_rename_dealer_code_order_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default='default_descrip', max_length=100),
        ),
    ]
