# Generated by Django 4.2.5 on 2023-09-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('pf_no', models.IntegerField(max_length=25)),
            ],
        ),
    ]
