# Generated by Django 4.2.5 on 2023-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pf_no', models.CharField(max_length=100)),
                ('dealer_code', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
                ('outlet', models.CharField(max_length=100)),
                ('start_time', models.TimeField(default='04:58:34', null=True)),
                ('end_time', models.TimeField(default='04:58:34', null=True)),
                ('visit_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
