# Generated by Django 4.2.5 on 2023-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end_time',
            field=models.TimeField(default='09:06:27', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(default='09:06:27', null=True),
        ),
    ]
